---

plugins:
  - babel
  - react

env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'eslint:recommended'
  - 'plugin:react/recommended'

settings:
  import/resolver:
    - node
    - webpack
  react:
    version: detect

rules:
  no-console: 0
  import/extensions: 0
  react/prop-types: 0
